// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://caomnmdtdoaclhbgbyyl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNhb21ubWR0ZG9hY2xoYmdieXlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3MTU3MTIsImV4cCI6MjA1ODI5MTcxMn0.kAIhttuAs6AU60o7Dnwf0eEMopoEmg42fQ-EYLIoFFg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);